name: Docker Image CI
on:
    release:
        types: [published]

jobs:

  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the Docker image (tag and latest)
      run: docker build . --file BuildImageUbuntu/Dockerfile --tag dockeratso/ubuntu-dotnet-core-sdk-opencvsharp:${{steps.vars.outputs.tag}} --tag dockeratso/ubuntu-dotnet-core-sdk-opencvsharp:latest
    - name: Push the Docker image with tag
      run: docker push dockeratso/ubuntu-dotnet-core-sdk-opencvsharp:${{steps.vars.outputs.tag}}
    - name: Push the Docker image as latest
      run: docker push dockeratso/ubuntu-dotnet-core-sdk-opencvsharp:latest
      
  build_nvidia_cuda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the Docker image (tag and latest)
      run: docker build . --file BuildImageNvidiaCuda/Dockerfile --tag dockeratso/nvidia-dotnet-core-sdk-opencvsharp:${{steps.vars.outputs.tag}} --tag dockeratso/nvidia-dotnet-core-sdk-opencvsharp:latest
    - name: Push the Docker image with tag
      run: docker push dockeratso/nvidia-dotnet-core-sdk-opencvsharp:${{steps.vars.outputs.tag}}
    - name: Push the Docker image as latest
      run: docker push dockeratso/nvidia-dotnet-core-sdk-opencvsharp:latest

    
