name: Test NuGet packages and Docker images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: dockeratso/ubuntu-dotnet-core-sdk-opencvsharp:4.3.0.20200527
    steps:
    - name: Test samples
      run: | 
        cd Samples
        dotnet build
        dotnet test
